name: Docker Image CI

# Controls when the action will be run
on:
  # triggers on push or pull request events on main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # base container to build on
    runs-on: ubuntu-latest
    # sequence of tasks in the build process
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Setup buildx environment
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/arm64,linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USER }}/cloudflare-ddns:latest
    
